
# try except 구문을 사용하여 예외처리하기
# 문법
#   try:
#       예외가 발생할 가능성이 있는 코드
#   except:
#       예외가 발생했을때 실행할 코드

# 설명:
#   예외가 발생할 가능성이 있는 코드를 모두 try구문에 넣고
#   예외가 발생했을때 실행할 코드르 모두 except구문안에 넣으면 된다.
#   이렇게 예외처리를 하면 어떤 상황에 예외가 발생하는지 완벽하게 이해하고 있지 않아도
#   프로그램이 강제로 죽는 것을 막을 수 있음

try:
    # 숫자를 입력받음
    number_input_a = int(input("정수입력>")) # 예외가 발생할 가능성이 있는 구문

    # 출력
    print("원의 반지름 : ", number_input_a)
    print("원의 둘레 : ", 2*3.14*number_input_a)
    print("원의 넓이 : ", 3.14*number_input_a*number_input_a)
except: # 예외가 발생했을때 실행하는 구문
    print("무언가 잘못되었습니다.")

print("그 다음 코드가 정상 출력 된 후 프로그램을 종료")

# 코드를 실행하고 정수로 변환할 수 없는 문자열을 입력
# -> 코드를 실행하면 프로그램이 강제로 종료되지 않고 예외처리 후 정상적으로 종료됨.